---
# vim: set ft=ansible:

- name: Install OpenStack repo for VirtualBMC
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
    owner: root
    group: root
    mode: 0644
  loop:
    - openstack-victoria.repo

- name: Install VirtualBMC packages and dependencies
  dnf:
    name:
      - python36
      - python3-virtualbmc
    state: latest
  become: true

- name: Enable VirtualBMC
  ansible.builtin.systemd:
    name: virtualbmc
    enabled: yes
    state: started
