---
# vim: set ft=ansible:

- name: "Wait for {{ ocp4_aio_baremetal_provider }} instance to come online..."
  wait_for_connection:
    timeout: 300

- name: Gather minimal facts
  setup:
    gather_subset: hardware

- name: Check system matches requirements
  assert:
    that:
      - ansible_memtotal_mb >= 100000
      - ansible_facts['os_family'] in ['RedHat','Rocky']
      - ansible_facts['distribution_major_version'] == '8'

- name: Install EPEL Repo
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: True
  become: True

- name: Install required base packages
  dnf:
    name:
      - wget
      - libvirt
      - qemu-kvm
      - virt-manager
      - virt-install
      - libguestfs
      - libguestfs-tools
      - libguestfs-xfs
      - net-tools
      - sshpass
      - virt-what
      - nmap
      - lvm2
      - python3-libselinux
    state: latest
    skip_broken: yes
  become: True

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
    skip_broken: yes

- name: Prepare libvirt images storage VG
  lvg:
    vg: vg.libvirt
    pvs: /dev/nvme0n1,/dev/nvme1n1
  when: ocp4_aio_baremetal_provider == 'packet' or ocp4_aio_baremetal_provider == 'equinix_metal'

- name: Prepare libvirt images storage LV
  lvol:
    vg: vg.libvirt
    lv: lvimages
    size: 100%FREE
    opts: -i 2 -I 4
  when: ocp4_aio_baremetal_provider == 'packet' or ocp4_aio_baremetal_provider == 'equinix_metal'

- name: Create filesystem on libvirt storage LV
  filesystem:
    fstype: ext4
    dev: /dev/vg.libvirt/lvimages
  when: ocp4_aio_baremetal_provider == 'packet' or ocp4_aio_baremetal_provider == 'equinix_metal'

- name: mount libvirt images backend storage if needed
  mount:
    path: /var/lib/libvirt/images
    src: /dev/vg.libvirt/lvimages
    fstype: ext4
    state: mounted
  when: ocp4_aio_baremetal_provider == 'packet' or ocp4_aio_baremetal_provider == 'equinix_metal'

- name: Enable Libvirt
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Enable Chronyd NTP Server
  ansible.builtin.replace:
    path: /etc/chrony.conf
    regexp: '^#local stratum 10'
    replace: 'local stratum 10'

- name: Enable Chronyd NTP Server
  ansible.builtin.replace:
    path: /etc/chrony.conf
    regexp: '^#allow 192.168.0.0/16'
    replace: allow 192.168.123.0/24

- name: Restart Chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted 
