- name: Install common base packages
  import_tasks: common.yml

- name: Install software for IPI deployments
  include_tasks: base_software_ipi.yml
  when: >-
    ocp4_aio_infra_role_base_software_deploy_type in ['ipi', 'sno']

- name: Install software for SNO
  include_tasks: base_software_sno.yml
  when: ocp4_aio_infra_role_base_software_deploy_type == 'sno'
